# Generated by Django 6.0.5 on 2026-06-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_status_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='kategori',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
