# Generated by Django 6.0.5 on 2026-06-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulayanan',
            name='max_person',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menulayanan',
            name='price_couple',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='menulayanan',
            name='price_family',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='menulayanan',
            name='price_group',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='menulayanan',
            name='price_self',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
