# Generated by Django 6.0.5 on 2026-06-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_menulayanan_max_person_menulayanan_price_couple_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulayanan',
            name='max_person',
        ),
        migrations.RemoveField(
            model_name='menulayanan',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
