# Generated by Django 6.0.5 on 2026-06-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_menulayanan_max_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drive_link',
            field=models.URLField(blank=True, null=True, verbose_name='Google Drive Link'),
        ),
    ]
