# Generated by Django 6.0.5 on 2026-07-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_drive_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('progress', 'On Progress'), ('finished', 'Selesai'), ('cancelled', 'Dibatalkan')], default='waiting', max_length=20),
        ),
    ]
