# Generated by Django 6.0.5 on 2026-08-08 20:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulayanan',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
