# Generated by Django 6.0.5 on 2026-08-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_menulayanan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='layanan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.menulayanan'),
        ),
    ]
